name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.16=py310hbdd6827_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.0.1=pyha191276_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=1.1.1w=h7f8727e_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyhc872135_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.6=haa1d7c7_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - pyzmq=27.1.0=py310hcf8288c_0
  - readline=8.3=hc2a1206_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py310h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - pip:
    - accelerate==1.11.0
    - aiofiles==24.1.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.12.15
    - aiohttp-socks==0.10.1
    - aiosignal==1.4.0
    - alembic==1.16.5
    - annotated-types==0.7.0
    - anyio==4.11.0
    - arrow==1.3.0
    - async-timeout==4.0.3
    - attrs==25.3.0
    - av==15.1.0
    - backoff==2.2.1
    - bcrypt==5.0.0
    - binaryornot==0.4.4
    - bitsandbytes==0.48.2
    - build==1.3.0
    - cachetools==5.5.2
    - certifi==2025.8.3
    - cffi==2.0.0
    - chardet==5.2.0
    - charset-normalizer==3.4.3
    - chromadb==1.1.0
    - click==8.1.8
    - click-default-group==1.2.4
    - coloredlogs==15.0.1
    - comfy-cli==1.5.1
    - comfyui-embedded-docs==0.2.6
    - comfyui-frontend-package==1.26.13
    - comfyui-workflow-templates==0.1.86
    - contourpy==1.3.2
    - cookiecutter==2.6.0
    - cryptography==46.0.1
    - cut-cross-entropy==25.1.1
    - cycler==0.12.1
    - dataclasses-json==0.6.7
    - datasets==4.3.0
    - diffusers==0.35.2
    - dill==0.4.0
    - distro==1.9.0
    - docstring-parser==0.17.0
    - docx==0.2.4
    - docx2pdf==0.1.8
    - durationpy==0.10
    - einops==0.8.1
    - faiss-gpu-cu12==1.12.0
    - fastapi==0.119.0
    - filelock==3.19.1
    - flatbuffers==25.9.23
    - fonttools==4.60.1
    - frozenlist==1.7.0
    - fsspec==2025.9.0
    - gitdb==4.0.12
    - gitpython==3.1.45
    - google-auth==2.40.3
    - googleapis-common-protos==1.70.0
    - grandalf==0.8
    - greenlet==3.2.4
    - grpcio==1.75.0
    - h11==0.16.0
    - h2==4.3.0
    - hf-transfer==0.1.9
    - hf-xet==1.1.10
    - hpack==4.1.0
    - httpcore==1.0.9
    - httptools==0.6.4
    - httpx==0.28.1
    - httpx-sse==0.4.1
    - huggingface-hub==0.35.1
    - humanfriendly==10.0
    - hyperframe==6.1.0
    - idna==3.10
    - importlib-resources==6.5.2
    - jinja2==3.1.6
    - joblib==1.5.2
    - jsonpatch==1.33
    - jsonpointer==3.0.0
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.9.1
    - kiwisolver==1.4.9
    - kornia==0.8.1
    - kornia-rs==0.1.9
    - kubernetes==33.1.0
    - langchain==0.3.27
    - langchain-community==0.3.30
    - langchain-core==0.3.76
    - langchain-text-splitters==0.3.11
    - langgraph==0.6.7
    - langgraph-checkpoint==2.1.1
    - langgraph-prebuilt==0.6.4
    - langgraph-sdk==0.2.9
    - langsmith==0.4.31
    - lxml==6.0.2
    - mako==1.3.10
    - markdown-it-py==4.0.0
    - markupsafe==3.0.2
    - marshmallow==3.26.1
    - matplotlib==3.10.7
    - matrix-nio==0.25.2
    - mdurl==0.1.2
    - mixpanel==4.11.1
    - mmh3==5.2.0
    - mpmath==1.3.0
    - msgspec==0.19.0
    - multidict==6.6.4
    - multiprocess==0.70.16
    - mypy-extensions==1.1.0
    - networkx==3.4.2
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.8.4.1
    - nvidia-cuda-cupti-cu12==12.8.90
    - nvidia-cuda-nvrtc-cu12==12.8.93
    - nvidia-cuda-runtime-cu12==12.8.90
    - nvidia-cudnn-cu12==9.10.2.21
    - nvidia-cufft-cu12==11.3.3.83
    - nvidia-cufile-cu12==1.13.1.3
    - nvidia-curand-cu12==10.3.9.90
    - nvidia-cusolver-cu12==11.7.3.90
    - nvidia-cusparse-cu12==12.5.8.93
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-nccl-cu12==2.27.3
    - nvidia-nvjitlink-cu12==12.8.93
    - nvidia-nvtx-cu12==12.8.90
    - oauthlib==3.3.1
    - onnxruntime==1.23.0
    - opentelemetry-api==1.37.0
    - opentelemetry-exporter-otlp-proto-common==1.37.0
    - opentelemetry-exporter-otlp-proto-grpc==1.37.0
    - opentelemetry-proto==1.37.0
    - opentelemetry-sdk==1.37.0
    - opentelemetry-semantic-conventions==0.58b0
    - orjson==3.11.3
    - ormsgpack==1.10.0
    - overrides==7.7.0
    - pandas==2.3.2
    - pandas-flavor==0.7.0
    - pathspec==0.12.1
    - patsy==1.0.2
    - peft==0.17.1
    - pillow==11.3.0
    - pingouin==0.5.5
    - pluggy==1.6.0
    - posthog==5.4.0
    - propcache==0.3.2
    - protobuf==6.32.1
    - psutil==7.1.0
    - pyarrow==22.0.0
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.2
    - pybase64==1.4.2
    - pycparser==2.23
    - pycryptodome==3.23.0
    - pydantic==2.11.9
    - pydantic-core==2.33.2
    - pydantic-settings==2.11.0
    - pygithub==2.8.1
    - pyjwt==2.10.1
    - pymupdf==1.26.5
    - pynacl==1.6.0
    - pypandoc==1.15
    - pyparsing==3.2.5
    - pypdf2==3.0.1
    - pypika==0.48.9
    - pyproject-hooks==1.2.0
    - python-docx==1.2.0
    - python-dotenv==1.1.1
    - python-multipart==0.0.20
    - python-slugify==8.0.4
    - python-socks==2.7.2
    - pytz==2025.2
    - pyyaml==6.0.3
    - questionary==2.1.1
    - referencing==0.36.2
    - regex==2025.9.18
    - requests==2.32.5
    - requests-oauthlib==2.0.0
    - requests-toolbelt==1.0.0
    - rich==14.1.0
    - rpds-py==0.27.1
    - rsa==4.9.1
    - ruff==0.13.2
    - safetensors==0.6.2
    - scikit-learn==1.7.2
    - scipy==1.15.3
    - seaborn==0.13.2
    - semver==3.0.4
    - sentence-transformers==5.1.1
    - sentencepiece==0.2.1
    - setuptools==80.9.0
    - shellingham==1.5.4
    - shtab==1.7.2
    - smmap==5.0.2
    - sniffio==1.3.1
    - soundfile==0.13.1
    - spandrel==0.4.1
    - sqlalchemy==2.0.43
    - sqlite-fts4==1.0.3
    - sqlite-utils==3.38
    - starlette==0.48.0
    - statsmodels==0.14.5
    - sympy==1.14.0
    - tabulate==0.9.0
    - tenacity==9.1.2
    - text-unidecode==1.3
    - threadpoolctl==3.6.0
    - tiktoken==0.12.0
    - tokenizers==0.22.1
    - toml==0.10.2
    - tomli==2.2.1
    - tomlkit==0.13.3
    - torch==2.8.0
    - torchao==0.14.1
    - torchaudio==2.8.0
    - torchsde==0.2.6
    - torchvision==0.23.0
    - tqdm==4.67.1
    - trampoline==0.1.2
    - transformers==4.56.2
    - triton==3.4.0
    - trl==0.23.0
    - typeguard==4.4.4
    - typer==0.19.2
    - types-python-dateutil==2.9.0.20250822
    - typing-inspect==0.9.0
    - typing-inspection==0.4.1
    - tyro==0.9.35
    - tzdata==2025.2
    - unpaddedbase64==2.1.0
    - unsloth==2025.10.12
    - unsloth-zoo==2025.10.13
    - urllib3==2.5.0
    - uv==0.8.22
    - uvicorn==0.37.0
    - uvloop==0.21.0
    - watchfiles==1.1.0
    - websocket-client==1.8.0
    - websockets==15.0.1
    - xarray==2025.6.1
    - xformers==0.0.32.post2
    - xxhash==3.5.0
    - yarl==1.20.1
    - zstandard==0.25.0
prefix: /home/alpaco/anaconda3/envs/test
